### ISSUE TITLE
Double checked a new controller

### ISSUE THREAD

**Issue by PeiyuQuan** [motorapp/Galil#20]
Hello,
There is a SMC-Galil controller at Xhuber website. The website is https://www.xhuber.com/en/products/3-control/smc-galil/
Could you help me double check this EPICS driver can work for SMC-Galil controller? It is a Galil DMC41, It seems no EPICS driver support it from the attachment table.

Thank you

![csm_controller_overview_b92bbb0852](https://github.com/motorapp/Galil/assets/41603034/1395442b-4660-41eb-ac7d-da1c49e7d910)

**Comment by motorapp** [comment]
Hello,
Yes, the Galil EPICS driver supports the 41x8 series controllers.
Kind regards,
Mark
